const artistImages: { [key: string]: any } = {
'2Hollis': require('../artist-images/2Hollis.jpg'),
'Action Bronson': require('../artist-images/Action Bronson.jpg'),
'Ahee': require('../artist-images/Ahee.jpg'),
'Alex Warren': require('../artist-images/Alex Warren.jpg'),
'Alexandra Kay': require('../artist-images/Alexandra Kay.jpg'),
'Aly & AJ': require('../artist-images/Aly & AJ.jpg'),
'Arcade Fire\'s "Santa Pirata"': require('../artist-images/Arcade Fire\'s Santa Pirata.jpg'),
'ATLiens': require('../artist-images/ATLiens.jpg'),
'Avril Lavigne': require('../artist-images/Avril Lavigne.jpg'),
'Azzecca': require('../artist-images/Azzecca.jpg'),
'Barry Can\'t Swim': require('../artist-images/Barry Can\'t Swim.jpg'),
'Beabadoobee': require('../artist-images/Beabadoobee.jpg'),
'Bebe Stockwell': require('../artist-images/Bebe Stockwell.jpg'),
'Big Gigantic': require('../artist-images/Big Gigantic.jpg'),
'Bilmuri': require('../artist-images/Bilmuri.jpg'),
'Bossman Dlow': require('../artist-images/Bossman Dlow.jpg'),
'Claptone': require('../artist-images/Claptone.jpg'),
'Crankdat': require('../artist-images/Crankdat.jpg'),
'Cults': require('../artist-images/Cults.jpg'),
'Dadi Freyr': require('../artist-images/Dadi Freyr.jpg'),
'Daniel Donato\'s Cosmic Country': require('../artist-images/Daniel Donato\'s Cosmic Country.jpg'),
'Destroy Boys': require('../artist-images/Destroy Boys.jpg'),
'Detox Unit': require('../artist-images/Detox Unit.jpg'),
'Die Spitz': require('../artist-images/Die Spitz.jpg'),
'Dispatch': require('../artist-images/DISPATCH.jpg'),
'Dogs in a Pile': require('../artist-images/Dogs in a Pile.jpg'),
'Dom Dolla': require('../artist-images/Dom Dolla.jpg'),
'Dope Lemon': require('../artist-images/Dope Lemon.jpg'),
'Eater': require('../artist-images/Eater.jpg'),
'Effin': require('../artist-images/Effin.jpg'),
'Flatland Cavalry': require('../artist-images/Flatland Cavalry.jpg'),
'Flipturn': require('../artist-images/flipturn.jpg'),
'Foster the People': require('../artist-images/Foster the People.jpg'),
'Gigi Perez': require('../artist-images/Gigi Perez.jpg'),
'Ginger Root': require('../artist-images/Ginger Root.jpg'),
'Glass Animals': require('../artist-images/Glass Animals.jpg'),
'Glorilla': require('../artist-images/Glorilla.jpg'),
'Goldie Boutilier': require('../artist-images/Goldie Boutilier.jpg'),
'Goose': require('../artist-images/Goose.jpg'),
'Gorgon City': require('../artist-images/Gorgon City.jpg'),
'GorillaT': require('../artist-images/GorillaT.jpg'),
'Grace Bowers': require('../artist-images/Grace Bowers.jpg'),
'Green Velvet': require('../artist-images/Green Velvet.jpg'),
'Hey, Nothing': require('../artist-images/hey, nothing.jpg'),
'Hot Mulligan': require('../artist-images/Hot Mulligan.jpg'),
'Hozier': require('../artist-images/Hozier.jpg'),
'Insane Clown Posse': require('../artist-images/Insane Clown Posse.jpg'),
'Inzo': require('../artist-images/Inzo.jpg'),
'Jack\'s Mannequin': require('../artist-images/Jack\'s Mannequin.jpg'),
'Jade Cicada': require('../artist-images/Jade Cicada.jpg'),
'James Arthur': require('../artist-images/James Arthur.jpg'),
'Jessie Murph': require('../artist-images/Jessie Murph.jpg'),
'Joey Valence & Brae': require('../artist-images/Joey Valence and Brae.jpg'),
'John Summit': require('../artist-images/John Summit.jpg'),
'JPEGMAFIA': require('../artist-images/JPEGMAFIA.jpg'),
'Justice': require('../artist-images/Justice.jpg'),
'King Gizzard & The Lizard Wizard': require('../artist-images/King Gizzard & The Lizard Wizard.jpg'),
'Kitchen Dwellers': require('../artist-images/Kitchen Dwellers.jpg'),
'Leon Thomas': require('../artist-images/Leon Thomas.jpg'),
'Levity': require('../artist-images/Levity.jpg'),
'LSZee': require('../artist-images/LSZee.jpg'),
'Luke Combs': require('../artist-images/Luke Combs.jpg'),
'Mannequin Pussy': require('../artist-images/Mannequin Pussy.jpg'),
'Marcus King': require('../artist-images/Marcus King.jpg'),
'Marina': require('../artist-images/Marina.jpg'),
'Matt Champion': require('../artist-images/Matt Champion.jpg'),
'Max Styler': require('../artist-images/Max Styler.jpg'),
'Megadeth': require('../artist-images/Megadeth.jpg'),
'MJ Lenderman': require('../artist-images/MJ Lenderman.jpg'),
'Modest Mouse': require('../artist-images/Modest Mouse.jpg'),
'Mt. Joy': require('../artist-images/Mt. Joy.jpg'),
'Natasha Bedingfield': require('../artist-images/Natasha Bedingfield.jpg'),
'Nelly': require('../artist-images/Nelly.jpg'),
'Of the Trees': require('../artist-images/Of the Trees.jpg'),
'Olivia Rodrigo': require('../artist-images/Olivia Rodrigo.jpg'),
'Queens of the Stone Age': require('../artist-images/Queens of the Stone Age.jpg'),
'Rachel Chinouriri': require('../artist-images/Rachel Chinouriri.jpg'),
'Rainbow Kitten Surprise': require('../artist-images/Rainbow Kitten Surprise.jpg'),
'Raye': require('../artist-images/Raye.jpg'),
'Remi Wolf': require('../artist-images/Remi Wolf.jpg'),
'Remi Wolf\'s 1970\'s Pool Party Superjam': require('../artist-images/Remi Wolf\'s 1970\'s Pool Party Superjam.jpg'),
'RL Grime': require('../artist-images/RL Grime.jpg'),
'Role Model': require('../artist-images/Role Model.jpg'),
'Rossy': require('../artist-images/Rossy.jpg'),
'Royel Otis': require('../artist-images/Royel Otis.jpg'),
'Saint Motel': require('../artist-images/Saint Motel.jpg'),
'Sammy Virji': require('../artist-images/Sammy Virji.jpg'),
'Slightly Stoopid': require('../artist-images/Slightly Stoopid.jpg'),
'Sofia Isella': require('../artist-images/Sofia Isella.jpg'),
'Tape B': require('../artist-images/Tape B.jpg'),
'The Droptines': require('../artist-images/The Droptines.jpg'),
'The Lemon Twigs': require('../artist-images/The Lemon Twigs.jpg'),
'The Red Clay Strays': require('../artist-images/The Red Clay Strays.jpg'),
'The Stews': require('../artist-images/The Stews.jpg'),
'Thee Sinseers and The Altons': require('../artist-images/Thee Sinseers and The Altons.jpg'),
'Tipper': require('../artist-images/Tipper.jpg'),
'Treaty Oak Revival': require('../artist-images/Treaty Oak Revival.jpg'),
'Tyla': require('../artist-images/Tyla.jpg'),
'Tyler, The Creator': require('../artist-images/Tyler, The Creator.jpg'),
'Vampire Weekend': require('../artist-images/Vampire Weekend.jpg'),
'Wallows': require('../artist-images/Wallows.jpg'),
'Wave to Earth': require('../artist-images/Wave to Earth.jpg'),
'What So Not': require('../artist-images/What So Not.jpg'),
'Wilderado': require('../artist-images/Wilderado.jpg'),
'Wisp': require('../artist-images/Wisp.jpg'),
'YDG': require('../artist-images/YDG.jpg'),
'Ziggy Alberts': require('../artist-images/Ziggy Alberts.jpg'),
'Zingara': require('../artist-images/Zingara.jpg'),
'Of the Trees B2B Tape B': require('../artist-images/Of the Trees B2B Tape B.jpg'),
'Parisi': require('../artist-images/Parisi.jpg'),
'Rebecca Black (DJ Set)': require('../artist-images/Rebecca Black.jpg'),
'Tinzo + Jojo': require('../artist-images/Tinzo + Jojo.jpg'),
'Tractorbeam': require('../artist-images/Tractorbeam.jpg'),
'John Summit B2B Dom Dolla': require('../artist-images/John Summit B2B Dom Dolla.jpg'),
'Big Gigantic (DJ Set)': require('../artist-images/Big Gigantic.jpg'),
'Blacklizt': require('../artist-images/Blacklizt.jpg'),
'Cameron Winter': require('../artist-images/Cameron Winter.jpg'),
'Mary Droppinz': require('../artist-images/Mary Droppinz.jpg'),
'Melt': require('../artist-images/Melt.jpg'),
'Saxsquatch': require('../artist-images/Saxsquatch.jpg'),
'Arooj Aftab': require('../artist-images/Arooj Aftab.jpg'),
'Photay': require('../artist-images/Photay.jpg'),
'Post Sex Nachos': require('../artist-images/Post Sex Nachos.jpg'),
'Washed Out': require('../artist-images/Washed Out.jpg'),
'DJ Python': require('../artist-images/DJ Python.jpg'),
'Airrica': require('../artist-images/Airrica.jpg'),
'Kamino': require('../artist-images/Kamino.jpg'),
'Omnom': require('../artist-images/Omnom.jpg'),
'Ayybo': require('../artist-images/Ayybo.jpg'),
'it\'s murph': require('../artist-images/it\'s murph.jpg'),
};

export default artistImages;