const artistImages: { [key: string]: any } = {
    '49 Winchester': require('../artist-images/49 Winchester.jpg'),
    'Armand Hammer': require('../artist-images/Armand Hammer.jpg'),
    'Ashnikko': require('../artist-images/Ashnikko.jpg'),
    'Baby Queen': require('../artist-images/Baby Queen.jpg'),
    'BADBADNOTGOOD': require('../artist-images/BADBADNOTGOOD.jpg'),
    'Bakar': require('../artist-images/Bakar.jpg'),
    'BigXthaPlug': require('../artist-images/BigXthaPlug.jpg'),
    'Bonny Light Horseman': require('../artist-images/Bonny Light Horseman.jpg'),
    'Brittany Howard': require('../artist-images/Brittany Howard.jpg'),
    'Cage the Elephant': require('../artist-images/Cage the Elephant.jpg'),
    'Carly Rae Jepsen': require('../artist-images/Carly Rae Jepsen.jpg'),
    'Chappell Roan': require('../artist-images/Chappell Roan.jpg'),
    'Charles Wesley Godwin': require('../artist-images/Charles Wesley Godwin.jpg'),
    'Chris Lake': require('../artist-images/Chris Lake.jpg'),
    'Cigarettes After Sex': require('../artist-images/Cigarettes After Sex.jpg'),
    'd4vd': require('../artist-images/d4vd.jpg'),
    'Dashboard Confessional Emo Superjam': require('../artist-images/Dashboard Confessional Emo Superjam.jpg'),
    'David Kushner': require('../artist-images/David Kushner.jpg'),
    'Diplo': require('../artist-images/Diplo.jpg'),
    'Disco Lines': require('../artist-images/Disco Lines.jpg'),
    'Dominic Fike': require('../artist-images/Dominic Fike.jpg'),
    'Dr. Fresch': require('../artist-images/Dr. Fresch.jpg'),
    'Durand Bernarr': require('../artist-images/Durand Bernarr.jpg'),
    'Eggy': require('../artist-images/Eggy.jpg'),
    'Ethel Cain': require('../artist-images/Ethel Cain.jpg'),
    'Faye Webster': require('../artist-images/Faye Webster.jpg'),
    'Fisher': require('../artist-images/Fisher.jpg'),
    'Four Tet': require('../artist-images/Four Tet.jpg'),
    'Fred again..': require('../artist-images/Fred again...jpg'),
    'Galantis': require('../artist-images/Galantis.jpg'),
    'Gary Clark Jr.': require('../artist-images/Gary Clark Jr..jpg'),
    'Geese': require('../artist-images/Geese.jpg'),
    'Goth Babe': require('../artist-images/Goth Babe.jpg'),
    'Greensky Bluegrass': require('../artist-images/Greensky Bluegrass.jpg'),
    'Gregory Alan Isakov': require('../artist-images/Gregory Alan Isakov.jpg'),
    'Grouplove': require('../artist-images/GROUPLOVE.jpg'),
    'GWAR': require('../artist-images/GWAR.jpg'),
    'Half Moon Run': require('../artist-images/Half Moon Run.jpg'),
    'Hamdi': require('../artist-images/Hamdi.jpg'),
    'HoneyLuv': require('../artist-images/Honeyluv.jpg'),
    'Idles': require('../artist-images/Idles.jpg'),
    'Interpol': require('../artist-images/Interpol.jpg'),
    'Irreversible Entaglements': require('../artist-images/Irreversible Entaglements.jpg'),
    'ISOxo': require('../artist-images/ISOxo.jpg'),
    'It\'s Murph': require('../artist-images/it\'s murph.jpg'),
    'Jake Wesley Rogers': require('../artist-images/Jake Wesley Rogers.jpg'),
    'Jason Isbell and the 400 Unit': require('../artist-images/Jason Isbell and the 400 Unit.jpg'),
    'Jessica Audiffred': require('../artist-images/Jessica Audiffred.jpg'),
    'Joe Russo\'s Almost Dead': require('../artist-images/Joe Russo\'s Almost Dead.jpg'),
    'Joey Bada$$': require('../artist-images/Joey Bada$$.jpg'),
    'Jon Batiste': require('../artist-images/Jon Batiste.jpg'),
    'Josiah & the Bonnevilles': require('../artist-images/Josiah & the Bonnevilles.jpg'),
    'Kasablanca': require('../artist-images/Kasablanca.jpg'),
    'Key Glock': require('../artist-images/Key Glock.jpg'),
    'Khruangbin': require('../artist-images/Khruangbin.jpg'),
    'Knock2': require('../artist-images/Knock2.jpg'),
    'Larkin Poe': require('../artist-images/Larkin Poe.jpg'),
    'Libianca': require('../artist-images/Libianca.jpg'),
    'Lizzy McAlpine': require('../artist-images/Lizzy McAlpine.jpg'),
    'Lovra': require('../artist-images/Lovra.jpg'),
    'LYNY': require('../artist-images/LYNY.jpg'),
    'Maggie Rogers': require('../artist-images/Maggie Rogers.jpg'),
    'Matt Maltese': require('../artist-images/Matt Maltese.jpg'),
    'Mdou Moctar': require('../artist-images/Mdou Moctar.jpg'),
    'Medium Build': require('../artist-images/Medium Build.jpg'),
    'Megan Thee Stallion': require('../artist-images/Megan Thee Stallion.jpg'),
    'Melanie Martinez': require('../artist-images/Melanie Martinez.jpg'),
    'Michigander': require('../artist-images/Michigander.jpg'),
    'MIKE': require('../artist-images/MIKE.jpg'),
    'mike.': require('../artist-images/mike..jpg'),
    'Militarie Gun': require('../artist-images/Militarie Gun.jpg'),
    'Milky Chance': require('../artist-images/Milky Chance.jpg'),
    'Nation of Language': require('../artist-images/Nation of Language.jpg'),
    'Neal Francis': require('../artist-images/Neal Francis.jpg'),
    'Neil Frances': require('../artist-images/Neil Frances.jpg'),
    'Ocie Elliot': require('../artist-images/Ocie Elliott.jpg'),
    'Oliver Heldens': require('../artist-images/Oliver Heldens.jpg'),
    'Parcels': require('../artist-images/Parcels.jpg'),
    'Post Malone': require('../artist-images/Post Malone.jpg'),
    'Pretty Lights': require('../artist-images/Pretty Lights.jpg'),
    'Red Hot Chili Peppers': require('../artist-images/Red Hot Chili Peppers.jpg'),
    'Reneé Rapp': require('../artist-images/Reneé Rapp.jpg'),
    'Róisín Murphy': require('../artist-images/Róisín Murphy.jpg'),
    'Ryan Beatty': require('../artist-images/Ryan Beatty.jpg'),
    'S.G. Goodman': require('../artist-images/S.G. Goodman.jpg'),
    'Say She She': require('../artist-images/Say She She.jpg'),
    'Sean Paul': require('../artist-images/Sean Paul.jpg'),
    'Seven Lions': require('../artist-images/Seven Lions.jpg'),
    'Shy FX': require('../artist-images/Shy FX.jpg'),
    'Sid Sriram': require('../artist-images/Sid Sriram.jpg'),
    'SVDDEN DEATH': require('../artist-images/SVDDEN DEATH.jpg'),
    'Taking Back Sunday': require('../artist-images/Taking Back Sunday.jpg'),
    'Tanner Usrey': require('../artist-images/Tanner Usrey.jpg'),
    'Teezo Touchdown': require('../artist-images/Teezo Touchdown.jpg'),
    'The Beaches': require('../artist-images/The Beaches.jpg'),
    'The Driver Era': require('../artist-images/The Driver Era.jpg'),
    'The Garden': require('../artist-images/The Garden.jpg'),
    'The Heavy Heavy': require('../artist-images/The Heavy Heavy.jpg'),
    'The Japanese House': require('../artist-images/The Japanese House.jpg'),
    'The Maine': require('../artist-images/The Maine.jpg'),
    'The Mars Volta': require('../artist-images/The Mars Volta.jpg'),
    'The Teskey Brothers': require('../artist-images/The Teskey Brothers.jpg'),
    'Thundercat': require('../artist-images/Thundercat.jpg'),
    'T-Pain': require('../artist-images/T-Pain.jpg'),
    'Trousdale': require('../artist-images/Trousdale.jpg'),
    'TSHA': require('../artist-images/Tsha.jpg'),
    'TV Girl': require('../artist-images/TV Girl.jpg'),
    'Two Friends': require('../artist-images/Two Friends.jpg'),
    'Vandelux': require('../artist-images/Vandelux.jpg'),
    'veggi': require('../artist-images/Veggi.jpg'),
    'Whyte Fang': require('../artist-images/Whyte Fang.jpg'),
    'Yves Tumor': require('../artist-images/Yves Tumor.jpg'),
    'Winyah': require('../artist-images/Winyah.jpg'),
    'Vincent Lima': require('../artist-images/Vincent Lima.jpg'),
    'Hans Williams': require('../artist-images/Hans Williams.jpg'),
    'Happy Landing': require('../artist-images/Happy Landing.jpg'),
    'Sawyer Hill': require('../artist-images/Sawyer Hill.jpg'),
    'The Foxies': require('../artist-images/The Foxies.jpg'),
    'Tors': require('../artist-images/Tors.jpg'),
    'Abby Holliday': require('../artist-images/Abby Holliday.jpg'),
    'Mon Rovía': require('../artist-images/Mon Rovía.jpg'),
    'Dan Spencer': require('../artist-images/Dan Spencer.jpg'),
    'Frayne Vibez': require('../artist-images/Frayne Vibez.jpg'),
    'Houseplant': require('../artist-images/Houseplant.jpg'),
    'Crowe Boys': require('../artist-images/Crowe Boys.jpg'),
    'Lowdown Brass Band': require('../artist-images/Lowdown Brass Band.jpg'),
    'Texas Hill': require('../artist-images/Texas Hill.jpg'),
    'Molly Grace': require('../artist-images/Molly Grace.jpg'),
    'Infinity Song': require('../artist-images/Infinity Song.jpg'),
    'Dean Johnson': require('../artist-images/Dean Johnson.jpg'),
    'Jobi Riccio': require('../artist-images/Jobi Riccio.jpg'),
    'Cale Tyson': require('../artist-images/Cale Tyson.jpg'),
    'Amira Elfeky': require('../artist-images/Amira Elfeky.jpg'),
    'Manwolves': require('../artist-images/Manwolves.jpg'),
    'Lily Fitts': require('../artist-images/Lily Fitts.jpg'),
    'Paul McDonald & The Mourning Doves': require('../artist-images/Paul McDonald & The Mourning Doves.jpg'),
    'Wolves of Glendale': require('../artist-images/Wolves of Glendale.jpg'),
    'Jive Talk': require('../artist-images/Jive Talk.jpg'),
    'Boot Scootin\' Boogie Nights': require('../artist-images/Boot Scootin\' Boogie Nights.jpg'),

};

export default artistImages;